# Generated by Django 4.0.6 on 2022-07-19 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_normaluser'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enroll_date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='course',
            name='educator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
